[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd FRONT && npm install"]

[phases.build]
cmds = ["cd FRONT && npm run build"]

[start]
cmd = "npx --prefix FRONT vite preview --host 0.0.0.0 --port $PORT"

