[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd FRONT && npm ci"]

[phases.build]
cmds = ["cd FRONT && npm run build"]

[start]
cmd = "cd FRONT && npx vite preview --host 0.0.0.0 --port $PORT"

